apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: hello-helidon
  name: bluegreen-demo
  labels:
    app: hello-helidon
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hello-helidon
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: hello-helidon-deployment
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: istio-ingress
