apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: helidontest-appconf
  namespace: hello-helidon
  annotations:
    version: v1.0.0
    description: "Non-JRF WebLogic Domain"
spec:
  components:
    - componentName: hello-helidon-component
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
                scraper: verrazzano-system/vmi-system-prometheus-0
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: hello-helidon-ingress
            spec:
              rules:
                - paths:
                    - path: "/greeting"
                      pathType: Prefix
