apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: helidon-component
  namespace: helidon-config
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: helidon-workload
      labels:
        app: hello-helidon
        version: v1
    spec:
      deploymentTemplate:
        metadata:
          name: helidon-deployment
        podSpec:
          containers:
            - name: helidon-container
              image: "iad.ocir.io/idivyfxzwa6h/helidon-test3/helidon-greet-app:1.1.0"
              ports:
                - containerPort: 8080
                  name: http
